pollme/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
	path('polls/', include('polls.urls', namespace='polls')),
	path('accounts/', include('accounts.urls', namespace="accounts"))

]

polls/urls.py
from django.urls import path

from . import views


app_name="polls"

urlpatterns = [
    path('list/', views.polls_list, name="list"),
    path('list/my_polls/', views.my_polls, name="my_polls"),
    path('add_poll/', views.add_poll, name="add_poll"),
    path('edit/<int:poll_id>/', views.edit_poll, name="edit_poll"),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name="add_choice"),
    path('edit/choice/<int:choice_id>/', views.edit_choice, name="edit_choice"),
    path('delete/choice/<int:choice_id>/', views.delete_choice, name="delete_choice_confirm"),
    path('delete/poll/<int:poll_id>/', views.delete_poll, name="delete_poll_confirm"),
    # polls/details/1/
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    # polla/detail/1/vote
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')
]

polls/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Poll(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	text = models.CharField(max_length=225)
	pub_date = models.DateField()

	def __str__(self):
		return self.text


	def user_can_vote(self, user):
		"""
			return fals if user hase already voted, else True
		"""
		user_votes = user.vote_set.all()
		qs = user_votes.filter(poll=self)
		if qs.exists():
			return False
		return True

	@property
	def num_votes(self):
		return self.vote_set.count() 


	def get_results_dict(self):
		"""
		Return a list of objects in the form:
		[
			#for each related choice
			{
				'text': choice_text,
				'num_votes': number of votes on that choice,
				'percentage': num_votes / poll.num_votes *100

			}
		]
		"""

		res = []
		for choice in self.choice_set.all():
			d = {}
			d['text'] = choice.choice_text
			d['num_votes'] = choice.num_votes
			if not self.num_votes:
				d['percentage'] = 0
			else:
				d['percentage'] = choice.num_votes / self.num_votes * 100
			res.append(d)
		return res


class Choice(models.Model):
	poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=255)

	def __str__(self):
		return "{} - {}".format(self.poll.text[:25], self.choice_text[:25]) 

	@property
	def num_votes(self):
		return self.vote_set.count()

class Vote(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
	choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

polls/forms.py
from django import forms

from .models import Choice, Poll

class PollForm(forms.ModelForm):

	choice1 = forms.CharField(
						label='First Choice', 
						max_length=100, 
						min_length=1,
						widget=forms.TextInput(attrs={'class':'form-control'})
						)
	choice2 = forms.CharField(
						label='Second Choice', 
						max_length=100, 
						min_length=1,
						widget=forms.TextInput(attrs={'class':'form-control'})
						)
	


	class Meta:
		model = Poll
		fields = ['text', 'choice1', 'choice2']
		widgets = {
			'text': forms.Textarea(attrs={"class":"form-control", "rows": 3, "cols": 20})
		}



class EditPollForm(forms.ModelForm):

	class Meta:
		model = Poll
		fields = ['text']
		widgets = {
			'text': forms.Textarea(attrs={"class":"form-control", "rows": 3, "cols": 20})
		}


class ChoiceForm(forms.ModelForm):


	class Meta:
		model = Choice
		fields = ['choice_text'] 
				

polls/views.py
import datetime

from django.db.models import Count
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse


from .models import Choice, Poll, Vote

from .forms import PollForm, EditPollForm, ChoiceForm

# Create your views here.


@login_required
def polls_list(request):
	"""
	Renders the polls_list.html template which list 
	all the currently available polls
	"""
	polls = Poll.objects.all()
	search_term=''

	# modify the the queryset before we pass t in the paginator

	if 'text' in request.GET:
		polls = polls.order_by('text')


	if 'pub_date' in request.GET:
		polls = polls.order_by('-pub_date')

						# num_votes is not a column in our models
	if 'num_votes' in request.GET:
		polls = polls.annotate(Count('vote')).order_by('-vote__count')


	if 'search' in request.GET:
		search_term = request.GET['search']
		polls=polls.filter(text__icontains=search_term) 

	paginator = Paginator(polls, 5)

	page = request.GET.get('page')
	polls = paginator.get_page(page)

	get_dict_copy = request.GET.copy()
	params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()

	context = {'polls': polls, 'params': params, 'search_term': search_term}
	return render(request, 'polls/polls_list.html', context)


def my_polls(request):
	# my_polls = Poll.objects.filter(owner=request.user)
	# print(my_polls)
	# This is the same as above
	my_polls = request.user.poll_set.all()
	# print(my_polls)
	paginator = Paginator(my_polls, 5)

	page = request.GET.get('page')
	my_polls = paginator.get_page(page)


	context = {'my_polls':my_polls}
	return render(request, 'polls/my_polls.html', context)



@login_required
def add_poll(request):
	if request.method == 'POST':
		form = PollForm(request.POST)
		if form.is_valid():
			new_poll = form.save(commit=False)
			new_poll.pub_date = datetime.datetime.now()
			new_poll.owner = request.user
			new_poll.save()
			new_choice1 = Choice(
									poll = new_poll,
									choice_text = form.cleaned_data['choice1']
								).save()
			new_choice2 = Choice(
									poll = new_poll,
									choice_text = form.cleaned_data['choice2']
								).save()
			messages.success(
								request, 
								'Poll and Choices added!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			return redirect('polls:my_polls')

	else:	
		form = PollForm()
	context = {'form': form}
	return render(request, 'polls/add_poll.html', context)



@login_required
def edit_poll(request, poll_id):
	poll = get_object_or_404(Poll, id=poll_id)
	if request.user != poll.owner:
		return redirect('/')

	if request.method == "POST":
		form = EditPollForm(request.POST, instance=poll)
		if form.is_valid():
			new_poll = form.save(commit=False)
			new_poll.pub_date = datetime.datetime.now()
			form.save()
			messages.success(
								request, 
								'Poll was successfully changed!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			return redirect('polls:list')


	else:
		form = EditPollForm(instance=poll)

	return render(request, 'polls/edit_poll.html', {'form': form, 'poll':poll})




@login_required
def delete_poll(request, poll_id):
	
	poll = get_object_or_404(Poll, id=poll_id)
	if request.user != poll.owner:
		return redirect('/')

	if request.method == 'POST':
		poll.delete()
		messages.success(
								request, 
								'Poll was successfully deleted!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			
			
		return redirect('polls:list')
		

	return render(request, 'polls/delete_poll_confirm.html', {'poll':poll})



@login_required
def add_choice(request, poll_id):
	poll = get_object_or_404(Poll, id=poll_id)
	if request.user != poll.owner:
		return redirect('/')

	if request.method == "POST":
		form = ChoiceForm(request.POST)
		if form.is_valid():
			new_choice = form.save(commit=False)
			new_choice.poll = poll
			new_choice.save()
			messages.success(
								request, 
								'Choice was successfully added!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			return HttpResponseRedirect(reverse("polls:edit_poll", args=(poll_id,)))

	else:
		form = ChoiceForm()

	return render(request, 'polls/add_choice.html', {'poll':poll, 'form':form})



@login_required
def edit_choice(request, choice_id):
	choice = get_object_or_404(Choice, id=choice_id)

	poll = get_object_or_404(Poll, id=choice.poll.id)
	if request.user != poll.owner:
		return redirect('/')

	if request.method == "POST":
		form = ChoiceForm(request.POST, instance=choice)
		if form.is_valid():
			form.save()
			messages.success(
								request, 
								'Choice was successfully changed!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			
			# change redirect to another path (polls:edit)
			return HttpResponseRedirect(reverse("polls:edit_poll", args=(poll.id,)))



	else:
		form = ChoiceForm(instance=choice)

	return render(request, 'polls/edit_choice.html', {'form': form, 'choice': choice})


@login_required
def delete_choice(request, choice_id):
	choice = get_object_or_404(Choice, id=choice_id)
	poll = get_object_or_404(Poll, id=choice.poll.id)
	if request.user != poll.owner:
		return redirect('/')

	if request.method == 'POST':
		choice.delete()
		messages.success(
								request, 
								'Choice was successfully deleted!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			
			
		return HttpResponseRedirect(reverse("polls:edit_poll", args=(poll.id,)))
		

	return render(request, 'polls/delete_choice_confirm.html', {'choice':choice})



@login_required
def poll_detail(request, poll_id):
	"""

	Render the poll_detail.html which allows a user to vote on the coices of a poll

	"""
	# poll = Poll.objects.get(id=poll_id)  // DoesNotExist
	poll = get_object_or_404(Poll, id=poll_id)
	user_can_vote = poll.user_can_vote(request.user)
	results = poll.get_results_dict()
	context = {'poll': poll, 'user_can_vote': user_can_vote,  'results': results}
	return render(request, 'polls/poll_detail.html', context)



@login_required
def poll_vote(request, poll_id):
	poll = get_object_or_404(Poll, id=poll_id)

	if not poll.user_can_vote(request.user):
		messages.error(request, 'You have already votted on this Poll!')
		return redirect('polls:detail', poll_id=poll_id)
		
	choice_id = request.POST.get('choice')
	if choice_id:
		choice = Choice.objects.get(id=choice_id)
		new_vote = Vote(user=request.user, poll=poll, choice=choice)
		new_vote.save()
		messages.success(
								request, 
								'You successfully voted!', 
								extra_tags='alert alert-success alert-dismissible fade show')
			
		
	else:
		messages.error(request, 'Please Select something!', extra_tags='alert alert-danger alert-dismissible fade show')
		return redirect('polls:detail', poll_id=poll_id)
	return redirect('polls:detail', poll_id=poll_id)
	
	

polls/templates/polls/add_choice.html
{% extends 'base.html' %}



{% block content %}

<div class="container">
	<h1 class="text-center">
		Add a new Choice
	</h1>
	<p class="text-center">{{poll}}</p>
	<div class="row">
		<div class="col-md-6 offset-md-3">
			
			<form action="" method="post">
			{% csrf_token %}		
			{% for field in form %}    			
				<div class="form-group">
					{{ field.label_tag }}
					{{ field }}
					{{ field.errors }}
				</div>

			{% endfor %}
			<input type="submit" class="btn btn-primary">



			</form>
		</div>
	</div>
</div>


{% endblock %}

polls/templates/polls/add_poll.html
{% extends 'base.html' %}


{% load static %}
{% block custom_css %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}


{% block content %}

<div class="container">
	<h1 class="text-center">Create your Poll</h1>
	<div class="row">
		<div class="col-md-6 offset-md-3">
			
			<form action="" method="post">
			{% csrf_token %}		
			{% for field in form %}
    			
				<div class="form-group">
					{{ field.label_tag }}
					{{ field }}
					{{ field.errors }}
				</div>

			{% endfor %}
			<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

polls/templates/polls/delete_choice_confirm.html
{% extends 'base.html' %}

{% block content %}



<div class="container">
	<h3 class="text-center">You are sure you want to delete "{{ choice.choice_text }}"?</h3>

	<div class="row">
		
		<div class="col-md-6 offset-md-3 text-center">
			
			<form action="" method="post">
				{% csrf_token %}
				<input type="submit" class="btn btn-danger" value="Sure!">
			</form>


		</div>

	</div>

</div>


{% endblock %}

polls/templates/polls/delete_poll_confirm.html
{% extends 'base.html' %}

{% block content %}



<div class="container">
	<h3 class="text-center">You are sure you want to delete "{{ poll.text }}"?</h3>

	<div class="row">
		
		<div class="col-md-6 offset-md-3 text-center">
			
			<form action="" method="post">
				{% csrf_token %}
				<input type="submit" class="btn btn-danger" value="Sure!">
			</form>


		</div>

	</div>

</div>


{% endblock %}

polls/templates/polls/edit_choice.html
{% extends 'base.html' %}

{% block content %}



<div class="container">
	<h1 class="text-center">Edit your Choice</h1>
	<div class="row">
		
		<div class="col-md-6 offset-md-3">
			
			<form action="" method="post">
			{% csrf_token %}		
			{% for field in form %}    			
				<div class="form-group">
					{{ field.label_tag }}
					{{ field }}
					{{ field.errors }}
				</div>			
				<input type="submit" class="btn btn-primary">


			{% endfor %}

			
			<a href="{% url 'polls:delete_choice_confirm' choice.id %}" class="btn btn-danger">
				<i class="far fa-trash-alt"></i>Delete	
			</a>
			





		</div>

	</div>

</div>






{% endblock %}

polls/templates/polls/edit_poll.html
{% extends 'base.html' %}



{% block content %}

<div class="container">
	<h1 class="text-center">Edit your Poll</h1>
	<div class="row">
		<div class="col-md-6 offset-md-3">
			
			<form action="" method="post">
			{% csrf_token %}		
			{% for field in form %}
    			
				<div class="form-group">
					{{ field.label_tag }}
					{{ field }}
					{{ field.errors }}
				</div>

			{% endfor %}
			<button type="submit" class="btn btn-primary">Submit</button>

			<a href="{% url 'polls:add_choice' poll.id %}" class="btn btn-warning">Add Choice <i class="fas fa-plus"></i></a>
			
			<a href="{% url 'polls:delete_poll_confirm' poll.id %}" class="btn btn-danger">
				<i class="far fa-trash-alt"></i>Delete	
			</a>


			<h3 class="text-center">Choices</h3>

			{% if messages %}
				
				    {% for message in messages %}
				    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
				    {{ message }}
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    				<span aria-hidden="true">&times;</span>
  					</button>
					</div>
				    
				    {% endfor %}
				
			{% endif %}

			{% for choice in poll.choice_set.all %}
				<div class="list-group-item">
					<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
					<a href="{% url 'polls:edit_choice' choice.id %}" class="float-right"><i class="far fa-edit"></i></a>

				</div>	
					
				{% endfor %}

			</form>
		</div>
	</div>
</div> 

{% endblock %}

polls/templates/polls/my_polls.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<h1 class="text-center">Your Polls {{ request.user }}</h1>
	<div class="row">
		
		<div class="col-md-6 offset-md-3">

			<!-- Error/Success Message -->

			{% if messages %}
				
				    {% for message in messages %}
				    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
				    {{ message }}
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    				<span aria-hidden="true">&times;</span>
  					</button>
					</div>
				    
				    {% endfor %}
				
			{% endif %}



			<!-- Add Button -->

			<a href="{% url 'polls:add_poll' %}" class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
			
			<!-- my_polls button -->
			
			<a href="{% url 'polls:list' %}" class="btn btn-primary">All Polls</a>
			

			<!-- Pagination -->
			<div class="pagination">
			    <span class="step-links">
			        {% if my_polls.has_previous %}
			            <a href="?page=1" class=" btn btn-primary btn-sm"><i class="fas fa-angle-double-left"></i></a>
			            <a href="?page={{ my_polls.previous_page_number }}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-left"></i></a>
					{% else %}
						 <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-double-left"></i></a>
			            <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-left"></i></a>
					{% endif %}

			        <span class="current">
			            {{ my_polls.number }} / {{ my_polls.paginator.num_pages }}
			        </span>

			        {% if my_polls.has_next %}
			            <a href="?page={{ my_polls.next_page_number }}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-right"></i></a>
			            <a href="?page={{ my_polls.paginator.num_pages }}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-double-right"></i></a>
			        {% else %}
			            <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-right"></i></a>
			            <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-double-right"></i></a>
					{% endif %}
			    </span>
			</div>
			




			<ul class="list-group">

				{% for poll in my_polls %}

					<li class="list-group-item">
						<a href="{% url 'polls:detail' poll.id %}"">{{ poll }}</a>
						{% if request.user == poll.owner %}
						<a href="{% url 'polls:edit_poll' poll.id %}" class="float-right"><i class="far fa-edit"></i></a>
						{% endif %}
						{% if request.user != poll.owner %}
						<div class="float-right">{{poll.owner}}</div>
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>

	</div>

</div>


{% endblock %}

polls/templates/polls/poll_detail.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}



{% block content %}

<div class="container">
	<h1 class="text-center">{{poll}} - {{poll.num_votes}} Vote(s)</h1>

	
	
	<div class="row">
		<div class="col-md-8 offset-md-2">
			{% if messages %}
				
				    {% for message in messages %}
				    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
				    {{ message }}
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    				<span aria-hidden="true">&times;</span>
  					</button>
					</div>
				    
				    {% endfor %}
				
			{% endif %}
			
			<!-- disable when it's not the owner -->
			{% if request.user == poll.owner %}
			<a 
				href="{% url 'polls:add_choice' poll.id %}" 
				class="btn btn-warning">
				Add Choice 
				<i class="fas fa-plus"></i>
			</a>
			{% endif %}


			<form action="{% url 'polls:vote' poll.id %}" method="post">
			{% csrf_token %}
			
			<div class="list-group">

				{% for choice in poll.choice_set.all %}
				<div class="list-group-item">
					<input 
						type="radio" 
						name="choice" 
						id="choice{{ forloop.counter }}" 
						value="{{choice.id}}">
					<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
				</div>	
					
				{% endfor %}
				{% if not user_can_vote %}
					{% for choice_dict in results %}
					{{ choice_dict.text }}
						<div class="progress mb-2 mt-2">
		  					<div class="progress-bar" role="progressbar" style="width: {{choice_dict.percentage}}%;">{{choice_dict.num_votes}}
		  					</div>
						</div>
					{% endfor %}
				{% else %}
					<p>Vote to see results!</p>
				{% endif %}	
			</div>

			<input type="submit" value="Vote" class="btn btn-primary" {% if not user_can_vote %}disabled{% endif %}>
		</div>
	</div>
	


	
	


	</form>

</div>


{% endblock %}

polls/templates/polls/polls_list.html
{% extends 'base.html' %}


{% load static %}
{% block custom_css %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}



{% block extra_head %}

<script 
	defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js" 
	integrity="sha384-EIHISlAOj4zgYieurP0SdoiBYfGJKkgWedPHH4jCzpCXLmzVsw1ouK59MuUtP4a1" 
	crossorigin="anonymous">
</script>

{% endblock %}


{% block content %}
<div class="container">
	<h1 class="text-center">Welcome to the Polls Lists</h1>
	<div class="row">
		<div class="col-md-8 offset-md-2">


			<!-- Error/Success Message -->

			{% if messages %}
				
				    {% for message in messages %}
				    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
				    {{ message }}
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    				<span aria-hidden="true">&times;</span>
  					</button>
					</div>
				    
				    {% endfor %}
				
			{% endif %}

			<!-- Filter Buttons -->
			<!-- A-Z -->

			<a 
				href="?text=True" 
				class="btn btn-{% if 'text' in request.GET %}warning{% else %}primary{% endif %}">A-Z
				
			</a>
			
			<!-- ordered by date created -->

			<a 
				href="?pub_date=True" 
				class="btn btn-{% if 'pub_date' in request.GET %}warning{% else %}primary{% endif %}">pub date 
				
			</a>
			
			<!-- ordered by number of votes -->

			<a 
				href="?num_votes=True" 
				class="btn btn-{% if 'num_votes' in request.GET %}warning{% else %}primary{% endif %}">Votes
				
			</a>



			<!-- Add Button -->

			<a href="{% url 'polls:add_poll' %}" class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
			
			<!-- my_polls button -->
			
			<a href="{% url 'polls:my_polls' %}" class="btn btn-primary">My Polls</a>
			

			<!-- Pagination -->

			<div class="pagination">
			    <span class="step-links">
			        {% if polls.has_previous %}
			            <a href="?page=1&{{params}}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-double-left"></i></a>
			            <a href="?page={{ polls.previous_page_number }}&{{params}}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-left"></i></a>
					{% else %}
						 <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-double-left"></i></a>
			            <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-left"></i></a>
					{% endif %}

			        <span class="current">
			            {{ polls.number }} / {{ polls.paginator.num_pages }}
			        </span>

			        {% if polls.has_next %}
			            <a href="?page={{ polls.next_page_number }}&{{params}}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-right"></i></a>
			            <a href="?page={{ polls.paginator.num_pages }}&{{params}}" class=" btn btn-primary btn-sm"><i class="fas fa-angle-double-right"></i></a>
			        {% else %}
			            <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-right"></i></a>
			            <a href="" class=" btn btn-secondary btn-sm"><i class="fas fa-angle-double-right"></i></a>
					{% endif %}
			    </span>
			</div>


			
			<!-- Search bar -->

			<form class="form-inline">
    			<input 
    				class="form-control mr-sm-2" 
    				type="search" 
    				placeholder="Search" 
    				aria-label="Search"
    				name="search"
    				value="{{search_term}}">
    			<button class="btn btn-outline-primary my-2 my-sm-2" type="submit">Search</button>
  			</form>

			<!-- Polls List -->

			<ul class="list-group">
				{% for poll in polls %}

					<li class="list-group-item">
						<a href="{% url 'polls:detail' poll.id %}"">{{ poll }}</a>
						{% if request.user == poll.owner %}
						<a href="{% url 'polls:edit_poll' poll.id %}" class="float-right"><i class="far fa-edit"></i></a>
						{% endif %}
						{% if request.user != poll.owner %}
						<div class="float-right">{{poll.owner}}</div>
						{% endif %}
					</li>
				{% endfor %}
			</ul>

		

		</div>
	</div>
</div>

{% endblock %}